/* =====================================================
   HORTUS PERENNIS — species data
   =====================================================
   Each entry is the contract the rest of the game renders and plans
   against. drawPlant() uses: form, h, sea, stem. The planner features
   use: type, space, spread, zones, native, eco, sun, moist.

   form    one of: bunchgrass | vertgrass | turkeyfoot | cloudgrass |
           oatgrass | cone | globe | spike | umbel (flat/domed corymb —
           yarrow, sedum, joe pye) | drumstick (buttons on wiry stems —
           burnet) | rosette (yucca sword-leaf crown) |
           archbell (arching Solomon's seal stems) |
           martagon (recurved lily bells) | pyramid (dense scilla raceme) |
           shrub (herbaceous mound) | fern | leafmound (hosta) |
           bulbcup (crocus/tulip/daffodil) | bush (woody shrub) |
           hydrangea (mophead/panicle shrub; look.bloomShape 'mop'|'panicle',
           look.headR sizes the flower heads) | tree (deciduous) | conifer
   type    grass | sedge | forb | bulb | shrub | tree — drives the tray
           categories. Bulbs live in their own layer (game.bulbs): they
           share tiles with perennials, bloom in earliest spring while
           the layer above is cut back, and vanish underground by summer
   bloomDay  optional: day-of-season the bloom peaks (bulbs sequence
           through spring: crocus 1, daffodil 3, muscari 4, tulip 6,
           camassia 9); species without it peak by phen (cool 5, mid 8,
           warm 11)
   bulbSeason optional for type:bulb: summer/fall keeps onion bulbs above
           ground outside the default spring-ephemeral window
   grow    woody only: years to mature size (establishment horizon —
           perennials use 10 growing days; a bur oak uses 10 years).
           Woody plants skip the spring cutback; they are structure.
   cw      woody only: mature canopy/twig width in px for the renderer
           (real-world spread stays in `spread`; trees shade a radius of
           spread/TILE_IN/2 tiles as they establish, and only sun:'part'
           plants can be planted in that shade)
   h       mature height in px (drives the renderer, not real units)
   space   on-center planting distance in inches (what you'd order/space by)
   spread  mature clump width in inches (info card / export notes)
   zones   [min,max] USDA hardiness range
   native  true if the straight species is native to the central US;
           false for cultivars/hybrids of garden (non-native) origin
   eco     EPA Level III ecoregions where the species is naturally at home;
           empty for non-natives (the natives-only filter is how you hide them)
   sun     full | part — primary light preference
   moist   dry | medium | moist — primary soil preference
   phen    cool | mid | warm — when it wakes in spring and peaks:
           cool-season plants (sedges, Calamagrostis, the spring
           bloomers) emerge first; warm-season prairie grasses and
           late risers like butterfly weed wait for real heat
   stem    optional stem color override (salvia's near-black stems)
   cv      optional named cultivars: { key:{ name:"'Cultivar'", note,
           ...overrides } }. Overrides merge over the straight species —
           h, stem, and per-season sea keys. Cultivar names are facts
           (nominative use; names aren't copyrightable) — plant patents
           restrict propagation, not depiction. Avoid trademarked TRADE
           names as branding; the cultivar name in quotes is safe.
   group   optional family handle ('coneflower'): species sharing it
           collapse into one tray button, and the chip row picks the
           species (each stays a full entry — own latin, zones, eco)
   chip    short label for this species' chip inside its group
   look    optional tweaks for the cone form, how the flower carries
           itself: rays (count), rayLen, rayW, droop (how hard the
           rays fall), stems, leaves, leafW, leafLen — leafy purpurea
           vs wispy pallida vs hard-reflexed atrorubens
   sea     per-season appearance, the Oudolf heart of the game:
           fol (foliage), bloom (flower this season, omit for none),
           seed (persistent seedhead/structure — fall/winter presence is
           the whole point), eye (cone center, coneflowers only)

   Accuracy matters more than prettiness — Kevin grows these.
*/
'use strict';

const PLANTS = {
  /* ---------- grasses & sedges: the matrix ---------- */
  bluestem:{ name:'Little Bluestem', latin:'Schizachyrium scoparium', form:'bunchgrass', type:'grass', h:46,
    space:18, spread:18, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Blue-green all summer, then the best copper in the prairie. Backlit in November it glows.',
    sea:{Spring:{fol:'#7fa07a'}, Summer:{fol:'#6e8f9b'}, Fall:{fol:'#c0623b',seed:'#efe6d3'}, Winter:{fol:'#a35a35',seed:'#f3ecdd'}},
    cv:{
      standingovation:{name:"'Standing Ovation'", note:'stiffly upright on blue legs, wine-red fall',
        sea:{Summer:{fol:'#5d7a9b'}, Fall:{fol:'#8a4a52',seed:'#efe6d3'}, Winter:{fol:'#7a4a48',seed:'#f3ecdd'}}},
      theblues:{name:"'The Blues'", note:'powder-blue stems all season',
        sea:{Summer:{fol:'#7d93b8'}, Fall:{fol:'#b06a4a',seed:'#efe6d3'}}},
    }},
  bigbluestem:{ name:'Big Bluestem', latin:'Andropogon gerardii', form:'turkeyfoot', type:'grass', h:78,
    space:24, spread:30, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains',
         'Western Corn Belt Plains','Southwestern Tablelands'],
    blurb:'King of the tallgrass — turkey-foot seedheads at eye level by September. The Flint Hills are made of it.',
    sea:{Spring:{fol:'#7d9a6e'}, Summer:{fol:'#6e8a8a'}, Fall:{fol:'#a8584a',seed:'#c9b08a'}, Winter:{fol:'#8a5040',seed:'#d6c4a4'}},
    cv:{
      blackhawks:{name:"'Blackhawks'", note:'foliage darkens to near-black purple',
        sea:{Summer:{fol:'#5e5468'}, Fall:{fol:'#4a3a4e',seed:'#c9b9a0'}, Winter:{fol:'#3f3442',seed:'#cdbfa8'}}},
    }},
  switchgrass:{ name:'Switchgrass', latin:'Panicum virgatum', form:'cloudgrass', type:'grass', h:66,
    space:24, spread:30, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains',
         'Western Corn Belt Plains','Southwestern Tablelands'],
    blurb:'A sturdy clump under an airy cloud of seed. Birds work it all winter.',
    sea:{Spring:{fol:'#7d9a5f'}, Summer:{fol:'#6f8f5a',bloom:'#d8b8c2'}, Fall:{fol:'#d9b85e',seed:'#e0cfae'}, Winter:{fol:'#c2a878',seed:'#e6d8ba'}},
    cv:{
      northwind:{name:"'Northwind'", note:'steel-blue, a strict vertical column',
        sea:{Summer:{fol:'#6e8f9b'}, Fall:{fol:'#d9b86a',seed:'#e8d9b0'}}},
      shenandoah:{name:"'Shenandoah'", note:'leaves flushed wine-red by July',
        sea:{Summer:{fol:'#8a6a62'}, Fall:{fol:'#a04438',seed:'#d8b8a0'}}},
    }},
  dropseed:{ name:'Prairie Dropseed', latin:'Sporobolus heterolepis', form:'bunchgrass', type:'grass', h:34,
    space:18, spread:24, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A fine-textured fountain that smells faintly of popcorn in bloom. Turns pumpkin-gold in fall.',
    sea:{Spring:{fol:'#7d9a5f'}, Summer:{fol:'#6f8f5a',seed:'#d8c9a8'}, Fall:{fol:'#d99a4e'}, Winter:{fol:'#c2a06a'}}},
  indiangrass:{ name:'Indiangrass', latin:'Sorghastrum nutans', form:'vertgrass', type:'grass', h:70,
    space:24, spread:24, zones:[4,9], native:true, sun:'full', moist:'medium', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'The tallgrass skyline. Bronze plumes in September; Kansas and Oklahoma both claim it as state grass.',
    sea:{Spring:{fol:'#7d9a6e'}, Summer:{fol:'#6f8f7a'}, Fall:{fol:'#c98a4a',seed:'#d9b87a'}, Winter:{fol:'#b08a5e',seed:'#e0cfa8'}}},
  sideoats:{ name:'Sideoats Grama', latin:'Bouteloua curtipendula', form:'oatgrass', type:'grass', h:30,
    space:15, spread:18, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Oat sprays hung neatly along one side of the stem. Purple-tinged in bloom, polite everywhere.',
    sea:{Spring:{fol:'#7d9a5f'}, Summer:{fol:'#7a9a6a',seed:'#b8a88a'}, Fall:{fol:'#c2925a',seed:'#d9c4a0'}, Winter:{fol:'#b09a78',seed:'#cdbb95'}}},
  karl:{ name:"Feather Reed Grass 'Karl Foerster'", latin:'Calamagrostis × acutiflora', form:'vertgrass', type:'grass', h:62,
    space:24, spread:24, zones:[4,9], native:false, sun:'full', moist:'medium', phen:'cool', eco:[],
    blurb:'The exclamation point. Vertical wheat-colored plumes by June that stand straight through snow.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#7d9a5f',seed:'#d9c08a'}, Fall:{fol:'#b89a5e',seed:'#d9c08a'}, Winter:{fol:'#b09a6e',seed:'#e0d2ae'}}},
  lovegrass:{ name:'Purple Lovegrass', latin:'Eragrostis spectabilis', form:'cloudgrass', type:'grass', h:30,
    space:18, spread:24, zones:[5,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Central Irregular Plains','Western Corn Belt Plains','Central Great Plains'],
    blurb:'A low native grass that throws a purple haze in late summer, then dries into a rolling tumble of seed.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#9a5a8e'}, Fall:{fol:'#b0825a',seed:'#a06486'}, Winter:{fol:'#a88a6a',seed:'#c2a07c'}}},
  pinkmuhly:{ name:'Pink Muhly Grass', latin:'Muhlenbergia capillaris', form:'cloudgrass', type:'grass', h:40,
    space:24, spread:30, zones:[5,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Fine green blades under a fall cloud of pink smoke. Best in lean soil, sharp drainage, and big repeating sweeps.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5f8a62'}, Fall:{fol:'#8a8a5e',bloom:'#d08aa8',seed:'#cfa0aa'}, Winter:{fol:'#a89072',seed:'#d8c0b6'}},
    cv:{
      whitecloud:{name:"'White Cloud'", note:'white plumes instead of pink',
        sea:{Fall:{fol:'#8a8a5e',bloom:'#efe6d3',seed:'#e4d8c8'}, Winter:{fol:'#a89072',seed:'#e8dccd'}}},
      lenca:{name:"'Lenca'", note:'deeper pink, compact and heavily plumed',
        h:34, sea:{Fall:{fol:'#8a8a5e',bloom:'#c86f9a',seed:'#bd8a9a'}, Winter:{fol:'#a89072',seed:'#d0a8aa'}}},
      fastforward:{name:"'Fast Forward'", note:'earlier bloom for shorter seasons',
        h:34, sea:{Fall:{fol:'#8a8a5e',bloom:'#d696b2',seed:'#cba0ac'}, Winter:{fol:'#a89072',seed:'#d8c0b6'}}},
    }},
  mexicanfeather:{ name:'Mexican Feather Grass', latin:'Nassella tenuissima', form:'oatgrass', type:'grass', h:32,
    space:18, spread:24, zones:[7,10], native:false, sun:'full', moist:'dry', phen:'warm', eco:[],
    blurb:'Fine blond hair in constant motion. Beautiful, but self-seeds freely and is invasive in some regions.',
    sea:{Spring:{fol:'#8a9a6a'}, Summer:{fol:'#a8b87a',seed:'#d8c99a'}, Fall:{fol:'#c8b878',seed:'#e0d2ae'}, Winter:{fol:'#b8a878',seed:'#d8c8a8'}}},
  tuftedhair:{ name:'Tufted Hairgrass', latin:'Deschampsia cespitosa', form:'cloudgrass', type:'grass', h:36,
    space:18, spread:24, zones:[4,8], native:true, sun:'part', moist:'moist', phen:'cool',
    eco:['Western Corn Belt Plains','High Plains'],
    blurb:'Cool-season tufts with airy gold seed in early summer. Better in moisture and light shade than hot dry prairie.',
    sea:{Spring:{fol:'#5f8a58'}, Summer:{fol:'#5d7a4c',seed:'#d8c99a'}, Fall:{fol:'#c2a85a',seed:'#d8c08a'}, Winter:{fol:'#b09a70',seed:'#d8c8a8'}}},
  sedge:{ name:'Plains Oval Sedge', latin:'Carex brevior', form:'bunchgrass', type:'sedge', h:22,
    space:12, spread:15, zones:[3,8], native:true, sun:'part', moist:'medium', phen:'cool',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A tidy cool-season tuft for bed edges and part shade. Green early, seed heads by June.',
    sea:{Spring:{fol:'#6f9a5a',seed:'#c2b48a'}, Summer:{fol:'#5d8a4c'}, Fall:{fol:'#9a8a5e'}, Winter:{fol:'#a89a78'}}},

  /* ---------- forbs: the flowering layer ---------- */
  echinacea:{ name:'Purple Coneflower', latin:'Echinacea purpurea', form:'cone', type:'forb', h:48,
    group:'coneflower', chip:'Purple',
    space:18, spread:18, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    look:{leaves:10, leafW:2.3, leafLen:0.38, stems:6, rays:8, rayLen:6, droop:2.5, rayW:2.4},
    blurb:'Pink petals around an orange cone in July; black seedheads that feed goldfinches all winter. The leafiest of the tribe.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#c76b8e',eye:'#b5651d'}, Fall:{fol:'#6b6248',seed:'#3a2c22'}, Winter:{fol:'#6b5d4a',seed:'#241a16'}},
    cv:{
      magnus:{name:"'Magnus'", note:'flat, deep-rose rays held wide',
        look:{leaves:10, leafW:2.3, leafLen:0.38, stems:6, rays:8, rayLen:6.5, droop:1, rayW:2.4},
        sea:{Summer:{fol:'#5d7a4c',bloom:'#b84a78',eye:'#a05518'}}},
      whiteswan:{name:"'White Swan'", note:'white rays around a green-gold cone',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0ead8',eye:'#b58a2e'}}},
    }},
  pallida:{ name:'Pale Purple Coneflower', latin:'Echinacea pallida', form:'cone', type:'forb', h:52,
    group:'coneflower', chip:'Pale Purple',
    space:18, spread:18, zones:[4,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    look:{leaves:5, leafW:1.2, leafLen:0.3, stems:4, rays:7, rayLen:8.5, droop:6, rayW:1.3},
    blurb:'Long pale ribbons drooping from the cone on wiry, near-naked stems, weeks before purpurea. The prairie original.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#d8a0b8',eye:'#8a5a3a'}, Fall:{fol:'#8a7a55',seed:'#3a2c22'}, Winter:{fol:'#6b5d4a',seed:'#241a16'}}},
  topeka:{ name:'Topeka Coneflower', latin:'Echinacea atrorubens', form:'cone', type:'forb', h:44,
    group:'coneflower', chip:'Topeka',
    space:15, spread:12, zones:[5,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains'],
    look:{leaves:4, leafW:1.4, leafLen:0.28, stems:4, rays:6, rayLen:5.5, droop:7, rayW:1.6},
    blurb:'The Flint Hills coneflower — deep wine rays swept back hard against the stem. Rare in the trade; grow it if you find it.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#a84a5e',eye:'#5e3a2a'}, Fall:{fol:'#7a6a4a',seed:'#352820'}, Winter:{fol:'#6b5d4a',seed:'#201812'}}},
  angustifolia:{ name:'Narrowleaf Coneflower', latin:'Echinacea angustifolia', form:'cone', type:'forb', h:30,
    group:'coneflower', chip:'Narrowleaf',
    space:12, spread:12, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['High Plains','Central Great Plains','Flint Hills','Southwestern Tablelands'],
    look:{leaves:6, leafW:1.3, leafLen:0.3, stems:4, rays:8, rayLen:5, droop:3, rayW:1.7},
    blurb:'The shortgrass echinacea — pink stars close to the ground on a taproot. The one the Plains tribes used for everything.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#c08aaa',eye:'#7a4a2e'}, Fall:{fol:'#8a7a55',seed:'#3a2c22'}, Winter:{fol:'#6b5d4a',seed:'#241a16'}}},
  paradoxa:{ name:'Yellow Coneflower', latin:'Echinacea paradoxa', form:'cone', type:'forb', h:42,
    group:'coneflower', chip:'Yellow',
    space:18, spread:15, zones:[4,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Ozark Highlands'],
    look:{leaves:5, leafW:1.4, leafLen:0.32, stems:5, rays:7, rayLen:8, droop:6.5, rayW:1.7},
    blurb:'The paradox: an echinacea in clear yellow, rays falling like a shuttlecock. Ozark glades only, but happy in any dry garden.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#e8c23a',eye:'#5e4a2a'}, Fall:{fol:'#8a7a55',seed:'#3a3024'}, Winter:{fol:'#6b5d4a',seed:'#2a241c'}}},
  rattlesnake:{ name:'Rattlesnake Master', latin:'Eryngium yuccifolium', form:'globe', type:'forb', h:52,
    space:18, spread:24, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Silver yucca-like leaves and pale spiky globes. Architectural in every season.',
    sea:{Spring:{fol:'#8fa8a0'}, Summer:{fol:'#8fa8a0',bloom:'#dfe8dd'}, Fall:{fol:'#9a9a86',seed:'#8a7a5e'}, Winter:{fol:'#8d8674',seed:'#6e5f48'}}},
  yucca:{ name:'Yucca', latin:'Yucca glauca', form:'rosette', type:'forb', h:62,
    space:36, spread:42, zones:[4,9], native:true, sun:'full', moist:'dry', phen:'cool',
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands'],
    look:{leaves:22, leafLen:0.5, leafW:2.4, filaments:false, stems:1, bells:8},
    blurb:'Great Plains soapweed yucca: evergreen blue-green swords, dry-soil structure, and cream bells on a summer stalk.',
    sea:{Spring:{fol:'#78918c',edge:'#9aa89a'}, Summer:{fol:'#6f8a86',edge:'#9aa89a',bloom:'#efe6d3'}, Fall:{fol:'#7d8672',edge:'#9a967e',seed:'#8a7158'}, Winter:{fol:'#747c6a',edge:'#9a927a',seed:'#a89272'}},
    cv:{
      colorguard:{name:"'Color Guard'", note:'bold yellow center with green edges, pink-bronze in winter',
        latin:'Yucca filamentosa', native:false, eco:[],
        sea:{Spring:{fol:'#d8c85a',edge:'#526c58'}, Summer:{fol:'#e2d068',edge:'#536f58',bloom:'#f2ead8'}, Fall:{fol:'#d0b84e',edge:'#5d6b50',seed:'#8a7158'}, Winter:{fol:'#c0a24a',edge:'#7a554e',seed:'#a89272'}}},
      brightedge:{name:"'Bright Edge'", note:'green swords with clean golden margins',
        latin:'Yucca filamentosa', native:false, eco:[],
        sea:{Spring:{fol:'#6e8a68',edge:'#d8c85a'}, Summer:{fol:'#637e62',edge:'#dcc85a',bloom:'#f2ead8'}, Fall:{fol:'#748060',edge:'#c4a848',seed:'#8a7158'}, Winter:{fol:'#6e7460',edge:'#b89a42',seed:'#a89272'}}},
      goldensword:{name:"'Golden Sword'", note:'wide gold-centered foliage, strong green margins',
        latin:'Yucca filamentosa', native:false, eco:[],
        sea:{Spring:{fol:'#d6c05a',edge:'#4f755c'}, Summer:{fol:'#dcca62',edge:'#4e735c',bloom:'#f3ead8'}, Fall:{fol:'#c9a84a',edge:'#5e7458',seed:'#8a7158'}, Winter:{fol:'#b89442',edge:'#6a6e54',seed:'#a89272'}}},
    }},
  monarda:{ name:'Wild Bergamot', latin:'Monarda fistulosa', form:'globe', type:'forb', h:44,
    space:24, spread:30, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Shaggy lavender mopheads in July, bee balm of the old prairie. Give it elbow room.',
    sea:{Spring:{fol:'#6f8f6e'}, Summer:{fol:'#6f8f6e',bloom:'#b88ac8'}, Fall:{fol:'#8a7a5a',seed:'#5e4a3a'}, Winter:{fol:'#7d7666',seed:'#4a3c30'}}},
  allium:{ name:"Ornamental Onion 'Millenium'", latin:"Allium 'Millenium'", form:'globe', type:'bulb', h:36,
    group:'allium', groupLabel:'Allium', chip:'Millenium',
    space:12, spread:12, zones:[4,8], native:false, sun:'full', moist:'medium', phen:'mid', bloomDay:9, bulbSeason:'summer', eco:[],
    look:{leaves:7, leafW:1.4, leafLen:0.32, stems:5, headR:5},
    blurb:'Rosy-purple drumsticks in high summer, mobbed by pollinators. Tan globes persist after frost.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#b06a9e'}, Fall:{fol:'#9a8a5e',seed:'#c2ad85'}, Winter:{fol:'#9a8f78',seed:'#cdbb95'}}},
  baptisia:{ name:'Blue False Indigo', latin:'Baptisia australis', form:'shrub', type:'forb', h:50,
    space:36, spread:42, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'cool',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains'],
    blurb:'Indigo spikes in spring on a shrub-like clump; charcoal seed pods that rattle in winter wind.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#4a5d9e'}, Summer:{fol:'#5d7a5c'}, Fall:{fol:'#6e6a55',seed:'#2c2620'}, Winter:{fol:'#5e574a',seed:'#1d1814'}}},
  creamindigo:{ name:'Cream Wild Indigo', latin:'Baptisia bracteata', form:'shrub', type:'forb', h:30,
    space:30, spread:36, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'cool',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains'],
    blurb:'Cream pea-flowers low to the ground in April, before the grasses wake. Slow but permanent.',
    sea:{Spring:{fol:'#7d9a6e',bloom:'#e8e0b8'}, Summer:{fol:'#6f8f6e'}, Fall:{fol:'#6e6a55',seed:'#2c2620'}, Winter:{fol:'#5e574a',seed:'#1d1814'}}},
  mountainmint:{ name:'Mountain Mint', latin:'Pycnanthemum muticum', form:'shrub', type:'forb', h:40,
    space:24, spread:30, zones:[4,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Silver-dusted bracts that look frosted in July. The single best pollinator plant in the bed.',
    sea:{Spring:{fol:'#7d9a6e'}, Summer:{fol:'#8fa89a',bloom:'#e8e8e0'}, Fall:{fol:'#8a8a70',seed:'#4e463a'}, Winter:{fol:'#7d7666',seed:'#3a342c'}}},
  amsonia:{ name:'Bluestar', latin:'Amsonia hubrichtii', form:'shrub', type:'forb', h:44,
    space:36, spread:36, zones:[5,8], native:true, sun:'full', moist:'medium', phen:'cool',
    eco:['Ouachita Mountains','Arkansas Valley'],
    blurb:'Steel-blue stars in spring, ferny green all summer, then pure molten gold in October.',
    sea:{Spring:{fol:'#7d9a6e',bloom:'#7d93c8'}, Summer:{fol:'#6f8f5a'}, Fall:{fol:'#e8b84a'}, Winter:{fol:'#b09a6e'}}},
  aster:{ name:'Aromatic Aster', latin:'Symphyotrichum oblongifolium', form:'shrub', type:'forb', h:32,
    group:'aster', chip:'Aromatic',
    space:24, spread:30, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Low violet-blue dome in October when everything else has quit. Smells of balsam when brushed.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#5d7a4c',bloom:'#8a6ab8'}, Winter:{fol:'#7a7060',seed:'#b8a88a'}}},
  newengland:{ name:'New England Aster', latin:'Symphyotrichum novae-angliae', form:'shrub', type:'forb', h:54,
    group:'aster', chip:'New England',
    space:24, spread:30, zones:[3,7], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'The tall one — royal-purple daisies with gold eyes, mobbed by migrating monarchs in September.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#5d7a4c',bloom:'#7a4a9e',eye:'#e8c23a'}, Winter:{fol:'#7a7060',seed:'#a89878'}}},
  smoothaster:{ name:'Smooth Blue Aster', latin:'Symphyotrichum laeve', form:'shrub', type:'forb', h:40,
    group:'aster', chip:'Smooth Blue',
    space:18, spread:24, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Clean blue-gray foliage no mildew touches, then clouds of pale lavender stars. The well-behaved aster.',
    sea:{Spring:{fol:'#7d93a0'}, Summer:{fol:'#6e8a90'}, Fall:{fol:'#6e8a90',bloom:'#9aa8d8',eye:'#e8c23a'}, Winter:{fol:'#8a8474',seed:'#b8a88a'}}},
  culvers:{ name:"Culver's Root", latin:'Veronicastrum virginicum', form:'spike', type:'forb', h:60,
    space:24, spread:24, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'White candelabra held high over whorled leaves in July — the vertical exclamation in a wet-prairie border.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#f0ede0'}, Fall:{fol:'#7a7050',seed:'#5e5240'}, Winter:{fol:'#6b6150',seed:'#4a4234'}}},
  yarrow:{ name:'Common Yarrow', latin:'Achillea millefolium', form:'umbel', type:'forb', h:30,
    space:18, spread:24, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'mid',
    look:{head:6, dome:0.35, stems:6, leaves:9, leafLen:0.4},
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Flat ferny plates over feathery foliage, drought be damned. Cut it back and it blooms again.',
    sea:{Spring:{fol:'#8a9a7a'}, Summer:{fol:'#7d8f6a',bloom:'#f0ece0'}, Fall:{fol:'#8a8a6e',seed:'#b8a880'}, Winter:{fol:'#7d7666',seed:'#a89878'}},
    cv:{
      terracotta:{name:"'Terracotta'", note:'burnt-orange fading to buff',
        sea:{Summer:{fol:'#7d8f6a',bloom:'#d08a4a'}, Fall:{fol:'#8a8a6e',seed:'#c2a06a'}}},
      moonshine:{name:"'Moonshine'", note:'sulphur-yellow over silver leaves',
        sea:{Spring:{fol:'#9aa890'}, Summer:{fol:'#8a9a80',bloom:'#e8c23a'}, Fall:{fol:'#9a9a78',seed:'#c2b482'}}},
    }},
  sedum:{ name:"Stonecrop 'Autumn Joy'", latin:'Hylotelephium', form:'umbel', type:'forb', h:28,
    space:18, spread:24, zones:[3,9], native:false, sun:'full', moist:'dry', phen:'mid', eco:[],
    look:{head:6.5, dome:0.6, stems:7, leaves:6, leafW:2.6, leafLen:0.36},
    blurb:'Broccoli-green all summer, dusty rose in September, then copper seedheads that hold the snow. Pure structure.',
    sea:{Spring:{fol:'#8aa882'}, Summer:{fol:'#7d9a78',bloom:'#cdd6c0'}, Fall:{fol:'#9a8a6e',bloom:'#c87a8e'}, Winter:{fol:'#8a6e52',seed:'#9a5e3e'}}},
  phlox:{ name:"Garden Phlox 'Jeana'", latin:'Phlox paniculata', form:'umbel', type:'forb', h:50,
    space:18, spread:24, zones:[4,8], native:true, sun:'full', moist:'medium', phen:'mid',
    look:{head:5.5, dome:0.5, stems:5, leaves:7, leafLen:0.3},
    eco:['Ozark Highlands','Central Irregular Plains'],
    blurb:'Mildew-proof and butterfly-mobbed — lavender-pink trusses scenting the July border. The Mt Cuba champion.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#d07aa8'}, Fall:{fol:'#7a7a55',seed:'#6e5f48'}, Winter:{fol:'#6b6150',seed:'#4a4234'}}},
  joepye:{ name:"Joe Pye Weed 'Gateway'", latin:'Eutrochium maculatum', form:'umbel', type:'forb', h:72,
    space:30, spread:36, zones:[3,8], native:true, sun:'full', moist:'moist', phen:'warm', stem:'#5a3a44',
    look:{head:8, dome:0.6, stems:5, leaves:6, leafLen:0.3},
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A shrub-sized native with great dusky-mauve domes on wine-dark stems, humming with bees. Give it a wet back corner.',
    sea:{Spring:{fol:'#6f8f6e'}, Summer:{fol:'#5d7a5c',bloom:'#b07a92'}, Fall:{fol:'#7a6a55',seed:'#6e5244'}, Winter:{fol:'#6b5d4a',seed:'#4e3c30'}}},
  stachys:{ name:"Betony 'Hummelo'", latin:'Stachys monnieri', form:'spike', type:'forb', h:24,
    space:18, spread:18, zones:[4,8], native:false, sun:'full', moist:'medium', phen:'mid', eco:[],
    blurb:'Tidy rosettes throwing up rosy-violet bottlebrushes for weeks — the 2019 Perennial of the Year, and earns it.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#a04a8e'}, Fall:{fol:'#6b6248',seed:'#4a3c38'}, Winter:{fol:'#5e574a',seed:'#3a322c'}}},
  penstemon:{ name:'Foxglove Beardtongue', latin:'Penstemon digitalis', form:'spike', type:'forb', h:38,
    space:18, spread:18, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Spires of white bells over green rosettes in June, then mahogany seed stalks that stand till spring.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#f2efe6'}, Fall:{fol:'#7a6a50',seed:'#6e4a3a'}, Winter:{fol:'#6b5d4a',seed:'#52372c'}},
    cv:{
      huskersred:{name:"'Husker Red'", note:'maroon foliage, white bells flushed pink',
        sea:{Spring:{fol:'#8a4a4e'}, Summer:{fol:'#7a3a44',bloom:'#f0e2e2'}, Fall:{fol:'#6e3a3a',seed:'#6e4a3a'}, Winter:{fol:'#5e3a36',seed:'#52372c'}}},
      darktowers:{name:"'Dark Towers'", note:'deeper burgundy leaves, pink bells',
        sea:{Spring:{fol:'#6e3a48'}, Summer:{fol:'#5e2e3e',bloom:'#e8b8c8'}, Fall:{fol:'#522a34',seed:'#6e4a3a'}, Winter:{fol:'#46282e',seed:'#52372c'}}},
    }},
  butterfly:{ name:'Butterfly Weed', latin:'Asclepias tuberosa', form:'shrub', type:'forb', h:26,
    space:18, spread:18, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Screaming-orange umbels on a tough taproot. Monarchs raise their young on it.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d8a4c',bloom:'#e07a2e'}, Fall:{fol:'#9a8a5e',seed:'#9a8a6e'}, Winter:{fol:'#8a7a60',seed:'#6e5f48'}}},
  liatris:{ name:'Dotted Blazing Star', latin:'Liatris punctata', form:'spike', type:'forb', h:32,
    space:12, spread:12, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands'],
    blurb:'Purple bottlebrush spikes from a taproot that laughs at drought. Shortgrass royalty.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a'}, Fall:{fol:'#8a8a5e',bloom:'#9a5aae'}, Winter:{fol:'#9a8a6e',seed:'#c2b49a'}}},
  goldenrod:{ name:'Showy Goldenrod', latin:'Solidago speciosa', form:'spike', type:'forb', h:50,
    space:18, spread:18, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Dense golden wands in September. Blamed for hay fever it does not cause.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d8a4c'}, Fall:{fol:'#7a8a55',bloom:'#e8c23a'}, Winter:{fol:'#8a7a60',seed:'#b8a888'}}},
  salvia:{ name:"Salvia 'Caradonna'", latin:'Salvia nemorosa', form:'spike', type:'forb', h:38,
    group:'salvia', groupLabel:'Salvia', chip:'Caradonna',
    space:18, spread:15, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'cool', eco:[], stem:'#3a3038',
    blurb:'Near-black stems with violet spikes in waves from May. Cut nothing; the dark stems hold.',
    sea:{Spring:{fol:'#5d7a4c',bloom:'#5a3a8e'}, Summer:{fol:'#5d7a4c',bloom:'#6a4a9e'}, Fall:{fol:'#6b6248',seed:'#3a3030'}, Winter:{fol:'#5e574a',seed:'#2c2624'}}},
  salviaspecies:{ name:'Salvia', latin:'Salvia nemorosa', form:'spike', type:'forb', h:34,
    group:'salvia', groupLabel:'Salvia', chip:'Straight',
    space:18, spread:18, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'cool', eco:[],
    blurb:'The meadow sage baseline: violet-blue spires, aromatic foliage, and a clean early-summer vertical line.',
    sea:{Spring:{fol:'#5d7a4c',bloom:'#6a58a8'}, Summer:{fol:'#5d7a4c',bloom:'#6a58a8'}, Fall:{fol:'#6b6248',seed:'#5a4a44'}, Winter:{fol:'#5e574a',seed:'#3a302c'}},
    cv:{
      maynight:{name:"'May Night'", note:'deep violet-blue, compact and early',
        sea:{Spring:{fol:'#5d7a4c',bloom:'#4d408e'}, Summer:{fol:'#5d7a4c',bloom:'#5a469a'}}},
      bluehill:{name:"'Blue Hill'", note:'softer clear blue flowers',
        sea:{Spring:{fol:'#5d7a4c',bloom:'#6f86c8'}, Summer:{fol:'#5d7a4c',bloom:'#7892d0'}}},
      amethyst:{name:"'Amethyst'", note:'rose-lavender spires',
        sea:{Spring:{fol:'#5d7a4c',bloom:'#b06a9e'}, Summer:{fol:'#5d7a4c',bloom:'#b878a8'}}},
    }},
  echinops:{ name:'Blue Echinops', latin:'Echinops ritro', form:'globe', type:'forb', h:46,
    space:24, spread:24, zones:[3,8], native:false, sun:'full', moist:'dry', phen:'mid', eco:[],
    look:{leaves:7, leafW:1.6, leafLen:0.34, stems:5, headR:4.6, spokes:10},
    blurb:'Steel-blue globes over thistly silver foliage. Very architectural, very bee-heavy, not native prairie.',
    sea:{Spring:{fol:'#7d9388'}, Summer:{fol:'#728a84',bloom:'#5f78b8'}, Fall:{fol:'#8a8a76',seed:'#8a8068'}, Winter:{fol:'#7a7468',seed:'#6e6658'}}},
  calamint:{ name:'Lesser Calamint', latin:'Calamintha nepeta subsp. nepeta', form:'umbel', type:'forb', h:24,
    space:18, spread:24, zones:[5,8], native:false, sun:'full', moist:'dry', phen:'mid', eco:[],
    look:{head:5.5, dome:0.2, stems:8, leaves:8, leafLen:0.28},
    blurb:'Aromatic minty haze: hundreds of tiny pale flowers from summer into fall, useful as a soft edge.',
    sea:{Spring:{fol:'#7d8f6a'}, Summer:{fol:'#6f8f6e',bloom:'#e8e0ee'}, Fall:{fol:'#8a8a6e',bloom:'#e8e0ee',seed:'#b8a888'}, Winter:{fol:'#7d7666',seed:'#a89878'}}},
  agastache:{ name:'Anise Hyssop', latin:'Agastache foeniculum', form:'spike', type:'forb', h:48,
    space:18, spread:24, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    look:{leaves:8, leafW:1.8, leafLen:0.34, stems:6},
    blurb:'Licorice-scented native mint with lavender spikes and a long pollinator season. Short-lived, but generous.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#8a6ac0'}, Fall:{fol:'#7a7050',bloom:'#7d5aa8',seed:'#5e5248'}, Winter:{fol:'#6b5d4a',seed:'#4a4238'}},
    cv:{
      bluefortune:{name:"'Blue Fortune'", note:'sterile hybrid with fat lavender-blue spikes',
        native:false, eco:[], h:44, sea:{Summer:{fol:'#5d7a4c',bloom:'#8fa0d0'}, Fall:{fol:'#7a7050',bloom:'#7d8fbd',seed:'#5e5248'}}},
      goldenjubilee:{name:"'Golden Jubilee'", note:'chartreuse foliage under lavender flowers',
        native:false, eco:[], sea:{Spring:{fol:'#b7c65a'}, Summer:{fol:'#a8b85a',bloom:'#8a6ac0'}, Fall:{fol:'#b8a858',bloom:'#7d5aa8',seed:'#5e5248'}}},
    }},
  catmint:{ name:'Catmint', latin:'Nepeta x faassenii', form:'shrub', type:'forb', h:26,
    space:24, spread:30, zones:[3,8], native:false, sun:'full', moist:'dry', phen:'cool', eco:[],
    blurb:'A soft silver mound covered in lavender-blue flowers for weeks. Good edge plant, good bee traffic.',
    sea:{Spring:{fol:'#8a9a88',bloom:'#8a7ac0'}, Summer:{fol:'#7d8f84',bloom:'#8a7ac0'}, Fall:{fol:'#8a8474',seed:'#9a8aa8'}, Winter:{fol:'#7d766a',seed:'#8a7a88'}},
    cv:{
      walkerslow:{name:"'Walker's Low'", note:'classic long-blooming lavender-blue mound',
        h:30, sea:{Spring:{fol:'#8a9a88',bloom:'#7a6ac0'}, Summer:{fol:'#7d8f84',bloom:'#7a6ac0'}}},
      sixhills:{name:"'Six Hills Giant'", note:'larger, billowy, and informal',
        h:34, spread:36, sea:{Spring:{fol:'#8a9a88',bloom:'#7d73c8'}, Summer:{fol:'#7d8f84',bloom:'#7d73c8'}}},
      catspajamas:{name:"'Cat's Pajamas'", note:'compact with flowers held low on the stems',
        h:18, spread:20, sea:{Spring:{fol:'#8a9a88',bloom:'#796ad0'}, Summer:{fol:'#7d8f84',bloom:'#796ad0'}}},
    }},
  helenium:{ name:'Sneezeweed', latin:'Helenium autumnale', form:'cone', type:'forb', h:48,
    space:18, spread:24, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    look:{rays:13, rayLen:5, droop:3.5, rayW:1.6, leaves:8, leafLen:0.34, stems:7},
    blurb:'Domed gold daisies with a fat brown button, late summer into fall. Wet feet welcome; it never sneezes anyone.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#e8b438',eye:'#7a4a26'}, Fall:{fol:'#7a6a48',bloom:'#d99a2e',eye:'#6e3a22'}, Winter:{fol:'#6b5d4a',seed:'#2c2218'}},
    cv:{
      moerheim:{name:"'Moerheim Beauty'", note:'burnt copper-orange, fading rust',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#c85a2e',eye:'#5e2e1e'}, Fall:{fol:'#7a6a48',bloom:'#a8482a',eye:'#52261a'}}},
    }},
  rudbeckia:{ name:'Black-eyed Susan', latin:'Rudbeckia fulgida var. sullivantii', form:'cone', type:'forb', h:38,
    space:18, spread:24, zones:[3,9], native:true, sun:'full', moist:'medium', phen:'mid',
    eco:['Central Irregular Plains','Western Corn Belt Plains','Ozark Highlands'],
    look:{rays:12, rayLen:5.2, droop:1.2, rayW:1.8, leaves:9, leafLen:0.34, stems:7},
    blurb:'The perennial black-eyed Susan: gold daisies with dark cones, late-summer color, and winter seedheads for finches.',
    sea:{Spring:{fol:'#5f7f4d'}, Summer:{fol:'#58784a',bloom:'#e3aa2e',eye:'#3a2518'}, Fall:{fol:'#6f7048',bloom:'#d99a2e',eye:'#2c1c14',seed:'#3a2a20'}, Winter:{fol:'#625a45',seed:'#2a2018'}},
    cv:{
      goldsturm:{name:"'Goldsturm'", note:'classic compact gold daisies with strong black cones',
        h:34, look:{rays:12, rayLen:5.4, droop:0.8, rayW:1.9, leaves:9, leafLen:0.34, stems:8},
        sea:{Summer:{fol:'#58784a',bloom:'#e6b12f',eye:'#2f2118'}, Fall:{fol:'#6f7048',bloom:'#d59a2d',eye:'#2a1c14'}}},
      littlegoldstar:{name:"'Little Goldstar'", note:'shorter, buttony, very floriferous',
        h:25, space:15, spread:18, look:{rays:11, rayLen:4.4, droop:0.6, rayW:1.7, leaves:10, leafLen:0.32, stems:9},
        sea:{Summer:{fol:'#5d7f4d',bloom:'#e9b533',eye:'#302018'}, Fall:{fol:'#747448',bloom:'#d9a02e',eye:'#2a1c14'}}},
      vietteslittle:{name:"'Viette's Little Suzy'", note:'dwarf, neat, long-blooming gold flowers',
        h:24, space:15, spread:18, look:{rays:11, rayLen:4.2, droop:0.7, rayW:1.7, leaves:9, leafLen:0.3, stems:8},
        sea:{Summer:{fol:'#5d7f4d',bloom:'#e2a82e',eye:'#342218'}, Fall:{fol:'#747448',bloom:'#d0962b',eye:'#2a1c14'}}},
      americangoldrush:{name:"'American Gold Rush'", note:'disease-resistant dome with golden rays and dark cones',
        h:28, space:18, spread:24, look:{rays:12, rayLen:4.8, droop:0.8, rayW:1.8, leaves:10, leafLen:0.32, stems:9},
        sea:{Summer:{fol:'#637f55',bloom:'#e8b236',eye:'#2f2118'}, Fall:{fol:'#77724a',bloom:'#d99d30',eye:'#2a1c14'}}},
    }},
  sanguisorba:{ name:'Canadian Burnet', latin:'Sanguisorba canadensis', form:'drumstick', type:'forb', h:56,
    group:'burnet', chip:'Canadian',
    space:24, spread:30, zones:[3,7], native:true, sun:'full', moist:'moist', phen:'mid',
    eco:['Western Corn Belt Plains','Central Irregular Plains'],
    look:{stems:8, button:1.8, buttonLen:4.6},
    blurb:'White bottlebrushes nodding on tall wiry stems over a wet meadow in September. The native burnet.',
    sea:{Spring:{fol:'#6f8f6e'}, Summer:{fol:'#5d7a5c'}, Fall:{fol:'#6e8a6c',bloom:'#f0ede2',seed:'#b8a888'}, Winter:{fol:'#6b5d4a',seed:'#8a7a60'}}},
  greatburnet:{ name:'Great Burnet', latin:'Sanguisorba officinalis', form:'drumstick', type:'forb', h:42,
    group:'burnet', chip:'Great',
    space:18, spread:24, zones:[4,8], native:false, sun:'full', moist:'medium', phen:'mid', eco:[],
    look:{stems:9, button:1.5, buttonLen:2.4},
    blurb:'Tiny oxblood drumsticks floating on airy branched stems — pure Oudolf scatter through the grasses.',
    sea:{Spring:{fol:'#6f8f6e'}, Summer:{fol:'#5d7a5c',bloom:'#7a2e3a'}, Fall:{fol:'#7a6a55',bloom:'#5e2430',seed:'#4a2a2e'}, Winter:{fol:'#5e574a',seed:'#3a2024'}}},
  lilacsquirrel:{ name:"Burnet 'Lilac Squirrel'", latin:'Sanguisorba hakusanensis', form:'drumstick', type:'forb', h:34,
    group:'burnet', chip:'Lilac Squirrel',
    space:18, spread:18, zones:[4,8], native:false, sun:'full', moist:'medium', phen:'mid', eco:[],
    look:{stems:6, button:2.3, buttonLen:5.8},
    blurb:'Long fuzzy mauve-pink catkins drooping like bottle-brush tails over blue-green leaves. A conversation piece.',
    sea:{Spring:{fol:'#7d93a0'}, Summer:{fol:'#6e8a90',bloom:'#d089aa'}, Fall:{fol:'#8a8470',seed:'#b89a9e'}, Winter:{fol:'#7d7666',seed:'#9a8a82'}}},
  coreopsis:{ name:'Threadleaf Coreopsis', latin:'Coreopsis verticillata', form:'cone', type:'forb', h:28,
    group:'coreopsis', chip:'Threadleaf',
    space:18, spread:24, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Ozark Highlands','Central Irregular Plains'],
    look:{rays:8, rayLen:4.5, droop:1, rayW:1.6, leaves:5, leafW:1, leafLen:0.34, stems:7},
    blurb:'A haze of fine foliage spangled with gold stars all summer. Shear it once and it reblooms.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d8a4c',bloom:'#e8c23a',eye:'#c89a2a'}, Fall:{fol:'#7a8a55',bloom:'#d9b43a',eye:'#b8902a'}, Winter:{fol:'#8a7a60',seed:'#5e5240'}},
    cv:{
      moonbeam:{name:"'Moonbeam'", note:'soft lemon-cream, blooms for months',
        sea:{Summer:{fol:'#5d8a4c',bloom:'#eef0c2',eye:'#cdc878'}, Fall:{fol:'#7a8a55',bloom:'#e2e4b8',eye:'#c2bd72'}}},
      zagreb:{name:"'Zagreb'", note:'deep golden-yellow, tidy and tough',
        sea:{Summer:{fol:'#5d8a4c',bloom:'#f0a82a',eye:'#b8801e'}, Fall:{fol:'#7a8a55',bloom:'#e09a26',eye:'#a8741a'}}},
    }},
  lanceleaf:{ name:'Lanceleaf Coreopsis', latin:'Coreopsis lanceolata', form:'cone', type:'forb', h:30,
    group:'coreopsis', chip:'Lanceleaf',
    space:15, spread:18, zones:[4,9], native:true, sun:'full', moist:'dry', phen:'mid',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    look:{rays:8, rayLen:5.5, droop:1.5, rayW:2.4, leaves:6, leafLen:0.34, stems:5},
    blurb:'Big bright gold daisies on a tough prairie native — the roadside tickseed, happiest in lean dry ground.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#f0b828',eye:'#a86a1e'}, Fall:{fol:'#7a7050',seed:'#5e5240'}, Winter:{fol:'#6b5d4a',seed:'#4a4234'}}},
  talltickseed:{ name:'Tall Tickseed', latin:'Coreopsis tripteris', form:'cone', type:'forb', h:70,
    group:'coreopsis', chip:'Tall',
    space:24, spread:36, zones:[3,8], native:true, sun:'full', moist:'medium', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    look:{rays:8, rayLen:4.5, droop:1, rayW:1.6, leaves:7, leafLen:0.42, stems:9},
    blurb:'Head-high sprays of pale gold daisies with dark eyes, smelling faintly of anise. The back-of-border tickseed.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#5d7a4c',bloom:'#e8d048',eye:'#5a3a2a'}, Winter:{fol:'#8a7a60',seed:'#5e5240'}}},
  willowsunflower:{ name:'Willowleaf Sunflower', latin:'Helianthus salicifolius', form:'cone', type:'forb', h:76,
    space:24, spread:36, zones:[4,9], native:true, sun:'full', moist:'dry', phen:'warm',
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Southwestern Tablelands'],
    look:{rays:11, rayLen:4, droop:1, rayW:1.4, leaves:11, leafLen:0.55, stems:9},
    blurb:'A green fountain of willowy leaves all summer, then a tower of small gold suns in October. Plant it big.',
    sea:{Spring:{fol:'#7d9a6a'}, Summer:{fol:'#6f9a5a'}, Fall:{fol:'#7a8a55',bloom:'#f0b82a',eye:'#6e4a1e'}, Winter:{fol:'#8a7a60',seed:'#5e5240'}}},

  /* ---------- bulbs: the layer under everything ----------
     They share tiles with perennials and bloom while the upper layer
     is still cut back — the Oudolf bulb lasagne. */
  crocus:{ name:'Snow Crocus', latin:'Crocus tommasinianus', form:'bulbcup', type:'bulb', h:10,
    space:3, spread:3, zones:[3,8], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:1, eco:[],
    look:{stems:5, cup:2.6},
    blurb:'First color of the year — lavender cups in the snowmelt, gone before the grasses stir. Squirrel-proof, mostly.',
    sea:{Spring:{fol:'#6f9a5a',bloom:'#a98ad8',eye:'#e8b83a'}, Summer:{}, Fall:{}, Winter:{}}},
  daffodil:{ name:'Daffodil', latin:'Narcissus pseudonarcissus', form:'bulbcup', type:'bulb', h:22,
    space:6, spread:6, zones:[3,8], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:3, eco:[],
    look:{stems:3, cup:3.4},
    blurb:"Yellow trumpets the rodents won't touch. Plant once, count more every April.",
    sea:{Spring:{fol:'#5d8a4c',bloom:'#e8c23a',eye:'#e8902a'}, Summer:{}, Fall:{}, Winter:{}}},
  muscari:{ name:'Grape Hyacinth', latin:'Muscari armeniacum', form:'spike', type:'bulb', h:12,
    space:3, spread:3, zones:[4,8], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:4, eco:[],
    blurb:'Cobalt beads by the hundred. Let it run through the bulb lawn.',
    sea:{Spring:{fol:'#6f9a5a',bloom:'#4a5dae'}, Summer:{}, Fall:{}, Winter:{}}},
  tulip:{ name:'Species Tulip', latin:'Tulipa clusiana', form:'bulbcup', type:'bulb', h:18,
    space:5, spread:5, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'cool', bloomDay:6, eco:[],
    look:{stems:3, cup:3.2},
    blurb:'The wild kind that comes back — slim candy-striped cups that close at night.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#c0392b',eye:'#e8c23a'}, Summer:{}, Fall:{}, Winter:{}}},
  camassia:{ name:'Wild Hyacinth', latin:'Camassia scilloides', form:'spike', type:'bulb', h:30,
    space:6, spread:6, zones:[4,8], native:true, sun:'part', moist:'moist', phen:'cool', bloomDay:9,
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:"The prairie's own bulb — steeples of pale violet stars in late spring, then gone into the grass.",
    sea:{Spring:{fol:'#6f9a5a',bloom:'#8a8ac8'}, Summer:{}, Fall:{}, Winter:{}}},
  claudeshride:{ name:"Martagon Lily 'Claude Shride'", latin:'Lilium martagon', form:'martagon', type:'bulb', h:60,
    space:12, spread:12, zones:[2,7], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:5, bulbSeason:'summer', eco:[],
    look:{stems:1, whorls:5, flowers:7},
    blurb:'A martagon lily with whorled leaves and dark mahogany-red recurved bells. More woodland-edge than prairie, but excellent vertical punctuation.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#6f2638',eye:'#d8a846'}, Fall:{fol:'#9a8a5e',seed:'#7a5a48'}, Winter:{seed:'#7a5a48'}}},
  scillaperuviana:{ name:'Scilla peruviana', latin:'Scilla peruviana', form:'pyramid', type:'bulb', h:22,
    space:6, spread:8, zones:[7,10], native:false, sun:'full', moist:'dry', phen:'cool', bloomDay:10, eco:[],
    look:{leaves:9, leafW:1.8, leafLen:0.5, stems:1, headW:16, dots:42},
    blurb:'Portuguese squill: a late-spring cone of blue stars. Mediterranean, showy, and not fully hardy in cold prairie winters.',
    sea:{Spring:{fol:'#5d8a5c',bloom:'#3f63b8'}, Summer:{}, Fall:{fol:'#5d8a5c'}, Winter:{}}},
  puschkinia:{ name:'Puschkinia', latin:'Puschkinia scilloides var. libanotica', form:'spike', type:'bulb', h:8,
    space:3, spread:3, zones:[4,8], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:2, eco:[],
    look:{leaves:4, leafW:1, leafLen:0.42, stems:4},
    blurb:'Lebanon squill: tiny pale blue-and-white striped spring flowers, best as a quiet underplanting drift.',
    sea:{Spring:{fol:'#6f9a5a',bloom:'#dfe8f4'}, Summer:{}, Fall:{}, Winter:{}}},
  snowdrop:{ name:'Snowdrop', latin:'Galanthus nivalis', form:'bulbcup', type:'bulb', h:9,
    space:3, spread:3, zones:[3,7], native:false, sun:'part', moist:'medium', phen:'cool', bloomDay:0, eco:[],
    look:{stems:5, cup:2.4},
    blurb:'Tiny white bells for the first thaw, best scattered under deciduous shade before the canopy closes.',
    sea:{Spring:{fol:'#6f9a5a',bloom:'#f4f1e8',eye:'#7aa55a'}, Summer:{}, Fall:{}, Winter:{}}},
  noddingonion:{ name:'Nodding Onion', latin:'Allium cernuum', form:'globe', type:'bulb', h:30,
    group:'allium', groupLabel:'Allium', chip:'Nodding',
    space:6, spread:8, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'mid', bloomDay:9, bulbSeason:'summer',
    look:{leaves:7, leafW:1.1, leafLen:0.36, stems:5, nod:true, headR:3.5},
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A native summer onion with rose-pink umbels that bend at the neck, airy enough to thread through grasses.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#d08aa8'}, Fall:{fol:'#9a8a5e',seed:'#b8a888'}, Winter:{}}},
  prairieonion:{ name:'Prairie Onion', latin:'Allium stellatum', form:'globe', type:'bulb', h:32,
    group:'allium', groupLabel:'Allium', chip:'Prairie',
    space:6, spread:8, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'warm', bloomDay:3, bulbSeason:'fall',
    look:{leaves:6, leafW:1, leafLen:0.32, stems:5, headR:4.4},
    eco:['Flint Hills','Central Great Plains','High Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Autumn onion for dry prairie edges: grassy leaves, pink-purple starry umbels, and small tan seed globes after bloom.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a'}, Fall:{fol:'#8a8a5e',bloom:'#c478a8',seed:'#b8a888'}, Winter:{}}},
  alliumPinkJewel:{ name:"Allium 'Pink Jewel'", latin:"Allium 'Pink Jewel'", form:'globe', type:'bulb', h:34,
    group:'allium', groupLabel:'Allium', chip:'Pink Jewel',
    space:8, spread:8, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'mid', bloomDay:6, bulbSeason:'summer', eco:[],
    look:{leaves:6, leafW:1, leafLen:0.3, stems:4, headR:4.8, spokes:8},
    blurb:'Soft pink ornamental onion globes for early-summer punctuation, gentler than the purple drumstick types.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#d8a0b8'}, Fall:{fol:'#9a8a5e',seed:'#c2ad85'}, Winter:{seed:'#cdbb95'}}},
  alliumAtropurpureum:{ name:'Allium atropurpureum', latin:'Allium atropurpureum', form:'globe', type:'bulb', h:34,
    group:'allium', groupLabel:'Allium', chip:'Atropurpureum',
    space:6, spread:6, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'mid', bloomDay:7, bulbSeason:'summer', eco:[],
    look:{leaves:5, leafW:1, leafLen:0.3, stems:5, headR:4.2, spokes:8},
    blurb:'Wine-dark, open allium heads on slim stems. Good for threading small dark notes through grasses.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#5e2438'}, Fall:{fol:'#9a8a5e',seed:'#7a5a58'}, Winter:{seed:'#8a7068'}}},
  alliumChristophii:{ name:'Allium christophii', latin:'Allium cristophii', form:'globe', type:'bulb', h:26,
    group:'allium', groupLabel:'Allium', chip:'Christophii',
    space:10, spread:12, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'mid', bloomDay:5, bulbSeason:'summer', eco:[],
    look:{leaves:5, leafW:1, leafLen:0.3, stems:3, headR:6.4, spokes:14},
    blurb:'Star-of-Persia: huge metallic violet starbursts that dry into skeletal globes. A graphic bulb for the plan view too.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#9a78c8'}, Fall:{fol:'#9a8a5e',seed:'#b8a888'}, Winter:{seed:'#c8b898'}}},
  alliumRedMohican:{ name:"Allium 'Red Mohican'", latin:"Allium 'Red Mohican'", form:'globe', type:'bulb', h:36,
    group:'allium', groupLabel:'Allium', chip:'Red Mohican',
    space:6, spread:8, zones:[4,8], native:false, sun:'full', moist:'dry', phen:'mid', bloomDay:8, bulbSeason:'summer', eco:[],
    look:{leaves:5, leafW:1, leafLen:0.3, stems:4, headR:4.4, spokes:7, topknot:'#efe6d3'},
    blurb:'Burgundy allium heads with a pale topknot, odd in the best way. Use sparingly as a little exclamation point.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#6f8f5a',bloom:'#7a2432'}, Fall:{fol:'#9a8a5e',seed:'#7a5a58'}, Winter:{seed:'#8a7068'}}},

  /* ---------- shade perennials: under the canopy ---------- */
  hosta:{ name:'Hosta', latin:'Hosta hybrida', form:'leafmound', type:'forb', h:30,
    space:30, spread:36, zones:[3,9], native:false, sun:'part', moist:'medium', phen:'mid', eco:[],
    blurb:'The shade workhorse — broad ribbed leaves in a tidy mound, lavender scapes in July. Deer agree.',
    sea:{Spring:{fol:'#7a9a6a'}, Summer:{fol:'#6f8f5a',bloom:'#b8a8d8'}, Fall:{fol:'#c9b86a'}, Winter:{}},
    cv:{
      blueangel:{name:"'Blue Angel'", note:'huge blue-gray leaves',
        sea:{Spring:{fol:'#7e95a0'}, Summer:{fol:'#7a93a0',bloom:'#cfc8e8'}, Fall:{fol:'#b8ad7a'}, Winter:{}}},
      sumsubstance:{name:"'Sum and Substance'", note:'chartreuse, the brighter the shade the better',
        sea:{Spring:{fol:'#aac25a'}, Summer:{fol:'#a8c25a',bloom:'#cabfe0'}, Fall:{fol:'#c9b85a'}, Winter:{}}},
    }},
  ostrichfern:{ name:'Ostrich Fern', latin:'Matteuccia struthiopteris', form:'fern', type:'forb', h:55,
    space:36, spread:48, zones:[3,7], native:true, sun:'part', moist:'moist', phen:'cool',
    eco:['Western Corn Belt Plains'],
    blurb:'Vase of plumes shoulder-high in a damp corner; stiff fertile fronds stand all winter. Fiddleheads in April.',
    sea:{Spring:{fol:'#7aa55a'}, Summer:{fol:'#5d8a4c'}, Fall:{fol:'#a8893f',seed:'#6e4a32'}, Winter:{seed:'#6e4a32'}}},
  ladyfern:{ name:'Lady Fern', latin:'Athyrium filix-femina', form:'fern', type:'forb', h:36,
    space:24, spread:30, zones:[3,8], native:true, sun:'part', moist:'moist', phen:'cool',
    eco:['Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Lacy, fresh-green, and forgiving — the fern for the north side of anything.',
    sea:{Spring:{fol:'#8ab06a'}, Summer:{fol:'#6f9a55'}, Fall:{fol:'#b09a55'}, Winter:{}}},
  christmasfern:{ name:'Christmas Fern', latin:'Polystichum acrostichoides', form:'fern', type:'forb', h:30,
    space:24, spread:24, zones:[3,9], native:true, sun:'part', moist:'medium', phen:'cool',
    eco:['Ozark Highlands','Central Irregular Plains'],
    blurb:'Leathery fronds still green at Christmas, hence the name. Dry shade once settled.',
    sea:{Spring:{fol:'#5d8a52'}, Summer:{fol:'#4e7a48'}, Fall:{fol:'#4e7a48'}, Winter:{fol:'#3f5e42'}}},
  pennsedge:{ name:'Pennsylvania Sedge', latin:'Carex pensylvanica', form:'bunchgrass', type:'sedge', h:18,
    space:12, spread:15, zones:[3,8], native:true, sun:'part', moist:'dry', phen:'cool',
    eco:['Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A soft no-mow lawn for dry shade — ankle-high swirls under the oaks.',
    sea:{Spring:{fol:'#7aa55a',seed:'#c2b48a'}, Summer:{fol:'#6f9a55'}, Fall:{fol:'#a8945e'}, Winter:{fol:'#a89a78'}}},
  columbine:{ name:'Wild Columbine', latin:'Aquilegia canadensis', form:'globe', type:'forb', h:32,
    space:12, spread:15, zones:[3,8], native:true, sun:'part', moist:'medium', phen:'cool',
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Red-and-yellow lanterns nodding over lacy leaves in April, made for returning hummingbirds.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#c8503a'}, Summer:{fol:'#7a936a'}, Fall:{fol:'#9a8a5e',seed:'#5e5244'}, Winter:{seed:'#4a4238'}}},
  woodlandphlox:{ name:'Woodland Phlox', latin:'Phlox divaricata', form:'umbel', type:'forb', h:24,
    space:12, spread:18, zones:[3,8], native:true, sun:'part', moist:'medium', phen:'cool',
    look:{head:5.5, dome:0.25, stems:6, leaves:7, leafLen:0.34},
    eco:['Central Irregular Plains','Western Corn Belt Plains','Ozark Highlands'],
    blurb:'Soft blue-lavender spring flowers for open shade, with a low, loose woodland habit rather than prairie verticality.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#8fa8d8'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#8a8a5e',seed:'#b8a880'}, Winter:{}}},
  wildgeranium:{ name:'Wild Geranium', latin:'Geranium maculatum', form:'umbel', type:'forb', h:24,
    space:18, spread:24, zones:[3,8], native:true, sun:'part', moist:'medium', phen:'cool',
    look:{head:5, dome:0.15, stems:5, leaves:8, leafLen:0.32},
    eco:['Central Irregular Plains','Western Corn Belt Plains','Ozark Highlands'],
    blurb:'A sturdy native woodland geranium: palmate leaves, lilac-pink spring flowers, and quiet summer foliage.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#c890b8'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#9a8a5e',seed:'#8a7058'}, Winter:{}}},
  solomonsseal:{ name:"Solomon's Seal", latin:'Polygonatum biflorum', form:'archbell', type:'forb', h:38,
    space:18, spread:24, zones:[3,8], native:true, sun:'part', moist:'medium', phen:'cool',
    look:{stems:4, leaves:9, bells:5},
    eco:['Central Irregular Plains','Western Corn Belt Plains','Ozark Highlands'],
    blurb:'Arching shade stems with paired cream bells underneath, then blue-black berries and straw-yellow fall structure.',
    sea:{Spring:{fol:'#6f8f6e',bloom:'#ece8d8'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#c2a85a',seed:'#384058'}, Winter:{seed:'#5e5240'}}},
  bluebells:{ name:'Virginia Bluebells', latin:'Mertensia virginica', form:'spike', type:'forb', h:28,
    space:18, spread:18, zones:[3,8], native:true, sun:'part', moist:'moist', phen:'cool', bloomDay:3,
    look:{leaves:9, leafW:2.2, leafLen:0.42, stems:5},
    eco:['Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'The spring ephemeral everyone forgives for disappearing: pink buds opening to blue bells in moist woodland shade.',
    sea:{Spring:{fol:'#7f9f8a',bloom:'#7da6d8'}, Summer:{fol:'#7a936a'}, Fall:{}, Winter:{}}},
  heuchera:{ name:'Heuchera', latin:'Heuchera americana', form:'leafmound', type:'forb', h:24,
    space:18, spread:18, zones:[4,9], native:true, sun:'part', moist:'medium', phen:'cool',
    eco:['Central Irregular Plains','Western Corn Belt Plains','Ozark Highlands'],
    blurb:'American alumroot for shade texture: scalloped leaves, airy cream flower wands, and color all season.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#647f55',bloom:'#e8dcc8'}, Fall:{fol:'#8a6a62'}, Winter:{fol:'#6f6258'}},
    cv:{
      greenSpice:{name:"'Green Spice'", note:'silver-green leaves with darker veining',
        sea:{Spring:{fol:'#94a77c'}, Summer:{fol:'#8fa078',bloom:'#e8dcc8'}, Fall:{fol:'#9a8468'}, Winter:{fol:'#7a705f'}}},
      palacepurple:{name:"'Palace Purple'", note:'deep bronze-purple foliage',
        sea:{Spring:{fol:'#6f4d5a'}, Summer:{fol:'#5e3f4e',bloom:'#eadcca'}, Fall:{fol:'#6e3a46'}, Winter:{fol:'#4f343e'}}},
      caramel:{name:"'Caramel'", note:'warm amber leaves for bright shade',
        sea:{Spring:{fol:'#c79a58'}, Summer:{fol:'#bd8d4e',bloom:'#eadcca'}, Fall:{fol:'#b06f45'}, Winter:{fol:'#7a5640'}}},
    }},
  astilbe:{ name:'Astilbe', latin:'Astilbe chinensis', form:'spike', type:'forb', h:34,
    space:18, spread:24, zones:[3,8], native:false, sun:'part', moist:'moist', phen:'cool', eco:[],
    look:{leaves:9, leafW:1.5, leafLen:0.36, stems:6},
    blurb:'Feathery shade plumes over ferny foliage. It wants moisture; dry shade will make it sulk.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#d89ab0'}, Fall:{fol:'#9a8a5e',seed:'#b8a888'}, Winter:{seed:'#9a8a78'}},
    cv:{
      fanal:{name:"'Fanal'", note:'deep red plumes',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#9e2f3e'}, Fall:{fol:'#9a8a5e',seed:'#8a6a62'}}},
      bridalveil:{name:"'Bridal Veil'", note:'white plumes, bright in shade',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0ece0'}, Fall:{fol:'#9a8a5e',seed:'#c8b898'}}},
      visions:{name:"'Visions'", note:'compact lavender-pink plumes',
        h:26, sea:{Summer:{fol:'#5d7a4c',bloom:'#c07aa8'}, Fall:{fol:'#9a8a5e',seed:'#b08a98'}}},
    }},

  /* ---------- woody shrubs ---------- */
  leadplant:{ name:'Leadplant', latin:'Amorpha canescens', form:'bush', type:'shrub', h:36, cw:44,
    space:36, spread:36, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'mid', grow:3,
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:"Silver leaflets and violet spikes on a shrub the bison couldn't kill. Roots go sixteen feet down.",
    sea:{Spring:{fol:'#8a9a8a'}, Summer:{fol:'#7d8f7d',bloom:'#6a4a9e'}, Fall:{fol:'#8a8a70'}, Winter:{seed:'#3a342c'}}},
  sumac:{ name:'Fragrant Sumac', latin:'Rhus aromatica', form:'bush', type:'shrub', h:42, cw:78,
    space:72, spread:96, zones:[3,9], native:true, sun:'full', moist:'dry', phen:'mid', grow:4,
    eco:['Flint Hills','Central Great Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Glossy three-part leaves, knee to chest high, and the best scarlet fall on the dry side of the yard.',
    sea:{Spring:{fol:'#7d9a5f',bloom:'#e8d97a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#c0523a'}, Winter:{seed:'#a8504a'}},
    cv:{
      growlow:{name:"'Gro-Low'", note:'knee-high and twice as wide — living mulch', h:24, cw:90,
        sea:{Spring:{fol:'#7d9a5f',bloom:'#e8d97a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#c0523a'}, Winter:{seed:'#a8504a'}}},
    }},
  newjersey:{ name:'New Jersey Tea', latin:'Ceanothus americanus', form:'bush', type:'shrub', h:30, cw:48,
    space:36, spread:42, zones:[4,8], native:true, sun:'full', moist:'dry', phen:'mid', grow:3,
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'A foam of white over a tidy woody knot. Tea from the leaves once started a revolution, roughly.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d8a4c',bloom:'#f0efe2'}, Fall:{fol:'#8a8a5e'}, Winter:{seed:'#5e5248'}}},
  coralberry:{ name:'Coralberry', latin:'Symphoricarpos orbiculatus', form:'bush', type:'shrub', h:34, cw:64,
    space:48, spread:60, zones:[2,7], native:true, sun:'part', moist:'medium', phen:'mid', grow:3,
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'An easy thicket that holds its coral-pink berries on bare winter stems. Quail cover.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#9a8a5e',seed:'#c25a6e'}, Winter:{seed:'#b8506a'}}},

  /* ---------- hydrangeas: grouped by flower type ----------
     Four tray buttons (Mophead / Lacecap / Panicle / Oakleaf); each
     group's chip row lists its species + cultivars. */
  hydrangea:{ name:'Bigleaf Hydrangea', latin:'Hydrangea macrophylla', form:'hydrangea', type:'shrub', h:42, cw:72,
    group:'mophead', chip:'Bigleaf',
    space:48, spread:60, zones:[6,9], native:false, sun:'part', moist:'moist', phen:'mid', grow:3, eco:[],
    look:{bloomShape:'mop', headR:8},
    blurb:'The classic mophead — blue in acid soil, pink in sweet. Buds are tender, so give it a sheltered spot.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#4e7a48',bloom:'#6a8fc8'}, Fall:{fol:'#7a7050',bloom:'#8a7aae'}, Winter:{fol:'#6b5d4a',seed:'#b8a888'}},
    cv:{
      nikkoblue:{name:"'Nikko Blue'", note:'deep true-blue mopheads',
        sea:{Summer:{fol:'#4e7a48',bloom:'#4a78c8'}, Fall:{fol:'#7a7050',bloom:'#6a6ab0'}}},
      endlesssummer:{name:"'Endless Summer'", note:'reblooms on new wood — flowers even after a hard winter',
        sea:{Summer:{fol:'#4e7a48',bloom:'#6a9ad0'}, Fall:{fol:'#7a7050',bloom:'#8a8ac0'}}},
      citylineparis:{name:"'Cityline Paris'", note:'compact, vivid rose-red', h:30, cw:40,
        sea:{Summer:{fol:'#4e7a48',bloom:'#d0567e'}, Fall:{fol:'#7a7050',bloom:'#b04a6e'}}},
    }},
  smoothhydrangea:{ name:'Smooth Hydrangea', latin:'Hydrangea arborescens', form:'hydrangea', type:'shrub', h:44, cw:74,
    group:'mophead', chip:'Smooth',
    space:42, spread:54, zones:[3,9], native:true, sun:'part', moist:'medium', phen:'mid', grow:3,
    eco:['Ozark Highlands'],
    look:{bloomShape:'mop', headR:9},
    blurb:'The native woodland-edge hydrangea — dependable white domes every summer on new wood, so it never misses after a cold winter.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#eef0e2'}, Fall:{fol:'#8a8a5e',bloom:'#d8d8c0'}, Winter:{fol:'#6b5d4a',seed:'#b0a888'}},
    cv:{
      annabelle:{name:"'Annabelle'", note:'enormous pure-white mopheads, the classic', h:46, cw:78,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f2f4e8'}, Fall:{fol:'#8a8a5e',bloom:'#dcdcc4'}}},
      incrediball:{name:"'Incrediball'", note:'Annabelle with stronger stems that hold the heads up', h:48, cw:80,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f2f4ea'}, Fall:{fol:'#8a8a5e',bloom:'#dcdcc4'}}},
      invinciblespirit:{name:"'Invincibelle Spirit'", note:'the pink smooth hydrangea, reblooming',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#d884a4'}, Fall:{fol:'#8a8a5e',bloom:'#c07090'}}},
    }},
  bigleaflace:{ name:'Bigleaf Lacecap', latin:'Hydrangea macrophylla', form:'hydrangea', type:'shrub', h:40, cw:68,
    group:'lacecap', chip:'Bigleaf',
    space:48, spread:60, zones:[6,9], native:false, sun:'part', moist:'moist', phen:'mid', grow:3, eco:[],
    look:{bloomShape:'lacecap', headR:9},
    blurb:'The flat, elegant cousin of the mophead — a lace ring of showy florets around a beaded center. Reads quieter in a shady border.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#4e7a48',bloom:'#7a9ad0'}, Fall:{fol:'#7a7050',bloom:'#8a8ac0'}, Winter:{fol:'#6b5d4a',seed:'#9a8a70'}},
    cv:{
      twistnshout:{name:"'Twist-n-Shout'", note:'reblooming, pink to periwinkle by soil',
        sea:{Summer:{fol:'#4e7a48',bloom:'#a87ac0'}, Fall:{fol:'#7a7050',bloom:'#9a6ab0'}}},
      bluewave:{name:"'Blue Wave'", note:'the classic clear-blue lacecap',
        sea:{Summer:{fol:'#4e7a48',bloom:'#5a86cc'}, Fall:{fol:'#7a7050',bloom:'#7a7ab8'}}},
      lanarthwhite:{name:"'Lanarth White'", note:'white sterile ring over a blue eye',
        sea:{Summer:{fol:'#4e7a48',bloom:'#f0f0e6'}, Fall:{fol:'#7a7050',bloom:'#d8d8c8'}}},
    }},
  smoothlace:{ name:'Smooth Lacecap', latin:'Hydrangea arborescens', form:'hydrangea', type:'shrub', h:42, cw:70,
    group:'lacecap', chip:'Smooth',
    space:42, spread:54, zones:[3,9], native:true, sun:'part', moist:'medium', phen:'mid', grow:3,
    eco:['Ozark Highlands'],
    look:{bloomShape:'lacecap', headR:9},
    blurb:'The wild form of the native smooth hydrangea — open lace heads humming with native bees, hardy to the bone.',
    sea:{Spring:{fol:'#6f8f5a'}, Summer:{fol:'#5d7a4c',bloom:'#eef0e2'}, Fall:{fol:'#8a8a5e',bloom:'#d4d4bc'}, Winter:{fol:'#6b5d4a',seed:'#aaa088'}},
    cv:{
      haashalo:{name:"'Haas Halo'", note:'huge native lacecap, a pollinator magnet',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0f2e6'}, Fall:{fol:'#8a8a5e',bloom:'#d8d8c0'}}},
    }},
  serratahydrangea:{ name:'Mountain Hydrangea', latin:'Hydrangea serrata', form:'hydrangea', type:'shrub', h:36, cw:56,
    group:'lacecap', chip:'Mountain',
    space:36, spread:48, zones:[5,9], native:false, sun:'part', moist:'medium', phen:'mid', grow:3, eco:[],
    look:{bloomShape:'lacecap', headR:7},
    blurb:'A daintier, hardier lacecap than bigleaf — smaller leaves, smaller heads, far more reliable bloom in a cold year.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#6a86c8'}, Fall:{fol:'#8a4a52',bloom:'#9a7ab0'}, Winter:{fol:'#6b5d4a',seed:'#9a8a70'}},
    cv:{
      bluebird:{name:"'Bluebird'", note:'sky-blue lace over leaves that redden in fall',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#5a8ad0'}, Fall:{fol:'#8a4a52',bloom:'#7a8ac0'}}},
      tuffstuff:{name:"'Tuff Stuff'", note:'reblooming, bud-hardy pink-to-blue',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#c07aa8'}, Fall:{fol:'#8a4a52',bloom:'#a86ab0'}}},
    }},
  panniclehydrangea:{ name:'Panicle Hydrangea', latin:'Hydrangea paniculata', form:'hydrangea', type:'shrub', h:64, cw:92,
    group:'panicle', chip:'Panicle',
    space:60, spread:72, zones:[3,8], native:false, sun:'full', moist:'medium', phen:'mid', grow:4, eco:[],
    look:{bloomShape:'panicle', headR:9},
    blurb:'The tough, sun-loving, cold-hardy one — big conical plumes opening white and aging to rose. Dries on the stem all winter.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#f0ede0'}, Fall:{fol:'#7a7050',bloom:'#e0a8b0'}, Winter:{fol:'#6b5d4a',seed:'#cdb89a'}},
    cv:{
      limelight:{name:"'Limelight'", note:'huge lime-green cones cooling to cream',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#cbd89a'}, Fall:{fol:'#7a7050',bloom:'#e0c4a8'}}},
      littlelime:{name:"'Little Lime'", note:'dwarf Limelight for small beds', h:40, cw:60,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#cbd89a'}, Fall:{fol:'#7a7050',bloom:'#e0bca8'}}},
      vanillastrawberry:{name:"'Vanilla Strawberry'", note:'white aging to deep strawberry-red',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f4ede2'}, Fall:{fol:'#7a7050',bloom:'#d0586e'}}},
      quickfire:{name:"'Quick Fire'", note:'blooms early, fast to deep pink',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0e6dc'}, Fall:{fol:'#7a7050',bloom:'#c84a6a'}}},
      bobo:{name:"'Bobo'", note:'dwarf, smothered in white', h:34, cw:48,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f2efe4'}, Fall:{fol:'#7a7050',bloom:'#e6b0b4'}}},
      pinkywinky:{name:"'Pinky Winky'", note:'two-tone cones, white tips over pink base',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0e2e0'}, Fall:{fol:'#7a7050',bloom:'#dc8aa0'}}},
    }},
  oakleafhydrangea:{ name:'Oakleaf Hydrangea', latin:'Hydrangea quercifolia', form:'hydrangea', type:'shrub', h:52, cw:80,
    group:'oakleaf', chip:'Oakleaf',
    space:60, spread:72, zones:[5,9], native:false, sun:'part', moist:'medium', phen:'mid', grow:4, eco:[],
    look:{bloomShape:'panicle', headR:8},
    blurb:'A Southern native with oak-shaped leaves that burn wine-red in fall and white cones that age to dusty rose. Four-season structure.',
    sea:{Spring:{fol:'#5d7a4c'}, Summer:{fol:'#5d7a4c',bloom:'#f0ede0'}, Fall:{fol:'#7a2e3a',bloom:'#c89aa8'}, Winter:{fol:'#6b4a3a',seed:'#c2a888'}},
    cv:{
      snowqueen:{name:"'Snow Queen'", note:'upright white cones, deep burgundy fall leaves',
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f2efe4'}, Fall:{fol:'#7a2e3a',bloom:'#d0a8b0'}}},
      rubyslippers:{name:"'Ruby Slippers'", note:'compact; white cones flush to deep ruby', h:36, cw:54,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0ece0'}, Fall:{fol:'#6e2832',bloom:'#b04a5e'}}},
      alice:{name:"'Alice'", note:'large; foot-long white panicles', h:60, cw:90,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f2efe4'}, Fall:{fol:'#7a2e3a',bloom:'#cca0ac'}}},
      peewee:{name:"'Pee Wee'", note:'dwarf oakleaf for tight corners', h:38, cw:54,
        sea:{Summer:{fol:'#5d7a4c',bloom:'#f0ede0'}, Fall:{fol:'#7a323e',bloom:'#c89aa8'}}},
    }},

  /* ---------- trees ---------- */
  buroak:{ name:'Bur Oak', latin:'Quercus macrocarpa', form:'tree', type:'tree', h:120, cw:150,
    space:480, spread:840, zones:[3,8], native:true, sun:'full', moist:'dry', phen:'warm', grow:10,
    eco:['Flint Hills','Central Great Plains','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'The savanna king — corky bark, fringed acorns, two centuries of patience. Plant it for someone else.',
    sea:{Spring:{fol:'#7d9a5f'}, Summer:{fol:'#4e6e44'}, Fall:{fol:'#9a7a45'}, Winter:{fol:'#8a6e4e'}}},
  redbud:{ name:'Eastern Redbud', latin:'Cercis canadensis', form:'tree', type:'tree', h:70, cw:95,
    space:240, spread:300, zones:[4,9], native:true, sun:'part', moist:'medium', phen:'cool', grow:5,
    eco:['Flint Hills','Central Irregular Plains','Western Corn Belt Plains'],
    blurb:"Magenta flowers straight out of the bare branches in April, heart leaves after. The prairie edge's small tree.",
    sea:{Spring:{bloom:'#c75a8e'}, Summer:{fol:'#5d7a4c'}, Fall:{fol:'#e8c23a'}, Winter:{seed:'#5e4a3a'}}},
  cottonwood:{ name:'Eastern Cottonwood', latin:'Populus deltoides', form:'tree', type:'tree', h:140, cw:170,
    space:600, spread:900, zones:[3,9], native:true, sun:'full', moist:'moist', phen:'mid', grow:5,
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'The state tree of Kansas: fast, huge, glittering leaves, June cotton everywhere. Needs room and water.',
    sea:{Spring:{fol:'#8aa86a'}, Summer:{fol:'#6f9a4e',seed:'#f3efe5'}, Fall:{fol:'#e8c23a'}, Winter:{}}},
  redcedar:{ name:'Eastern Red Cedar', latin:'Juniperus virginiana', form:'conifer', type:'tree', h:90, cw:55,
    space:180, spread:240, zones:[2,9], native:true, sun:'full', moist:'dry', phen:'cool', grow:7,
    eco:['Flint Hills','Central Great Plains','High Plains','Southwestern Tablelands',
         'Central Irregular Plains','Western Corn Belt Plains'],
    blurb:'Native evergreen with blue juniper berries. Honest warning: off the yard it eats unburned prairie.',
    sea:{Spring:{fol:'#4e6e52'}, Summer:{fol:'#46624a'}, Fall:{fol:'#4e6650',seed:'#7a93a8'}, Winter:{fol:'#3f5a46',seed:'#7a93a8'}}},
};
const PLANT_KEYS = Object.keys(PLANTS);

/* Curated ecoregions for the region picker (EPA Level III, the prairie
   states this game grew up in). zone is the default USDA suggestion the
   picker pre-fills — gardeners can override it. Don't ship shapefiles. */
const REGIONS = [
  {name:'Flint Hills', zone:6,
   blurb:'Tallgrass prairie over limestone and chert — too rocky to plow, so it never was.'},
  {name:'Central Great Plains', zone:6,
   blurb:'Mixed-grass heart of Kansas; hot summers, honest wind.'},
  {name:'High Plains', zone:5,
   blurb:'Shortgrass country — dry, high, and tough as nails.'},
  {name:'Southwestern Tablelands', zone:6,
   blurb:'Red-rock breaks and canyons off the southwest shoulder of the plains.'},
  {name:'Central Irregular Plains', zone:6,
   blurb:'Rolling Osage country where tallgrass meets scattered oak.'},
  {name:'Western Corn Belt Plains', zone:5,
   blurb:'Loess hills and old tallgrass, mostly under corn now.'},
];
